config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root 'welcome#index'
  get 'loans/new'
  resources :books
  resources :users
  resources :loans



  # Session routes
	get 'login' => 'session#new'
	post 'login' => 'session#create'
	delete 'logout' => 'session#destroy'
	get 'logout' => 'session#destroy'

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

    def initialize(user)

      if user.librarian?
          can :manage, Loan
          can :manage, Book
          can :manage, User
          
      end

      if user.preceptor?
          can :manage, Loan
          can :read, Book
          can :read, User
      end

      if user.student?
          can :read, Loan, user_id: user.id
          can :read, Book
          cannot :read, User
      end

      if user.professor?
          can :read, Loan, user_id: user.id
          can :read, Book
          cannot :read, User
      end
    end
end


    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	has_many :loans
	has_many :users, through: :loans

	before_validation :set_state, on: :create

	def available?
		loans.where(state: "actived").or(loans.where(state: "expired")).count == 0
	end

	def available
		if self.available?
			self.state = "available"
			dispo = {"available" => "Disponible"}
			dispo[self.state]
		else
			self.state = "not available"
			no_dispo = {"not available" => "No Disponible"}
			no_dispo[self.state]
		end
	end

	def self.search(search)
  		authors = where("author LIKE ?", "%#{search}%")
  		names = where("name LIKE ?", "%#{search}%")
		Book.from("(#{authors.to_sql} UNION #{names.to_sql}) AS books")
	end

	def set_state
			self.state = "available"
	end


end

app/models/loan.rb
class Loan < ApplicationRecord
	belongs_to :user
	belongs_to :book

	before_validation :set_state, on: :create


	def self.search(search)
		users_id = where("user_id LIKE ?", "%#{search}%")
		states = where("state LIKE ?", "%#{search}%")
	Loan.from("(#{users_id.to_sql} UNION #{states.to_sql}) AS loans")
	end

	def set_state
	    self.state = "actived"
	end

	def estado
		estados = {"actived" => "Activo", "expired" => "Expirado", "finished" => "Finalizado"}
		estados[self.state]
	end

	#PARA PONER EL ESTADO DEL PRESTAMO EN VENCIDO (EXPIRED)
		def is_expired?
			if self.final_date < DateTime.now && self.state == "actived"
				 self.state = "expired"
				 self.save
			end
			self.state == "expired"
		end

		#LISTAR LOS PRESTAMOS VENCIDOS.
			def self.expired
				Loan.where(state: "expired")
			end

end

app/models/user.rb
class User < ApplicationRecord

	has_secure_password
	has_many :loans
	has_many :books, through: :loans



	def self.search(search)
      last_names = where("last_name LIKE ?", "%#{search}%")
      dnis = where("dni LIKE ?", "%#{search}%")
    Book.from("(#{last_names.to_sql} UNION #{dnis.to_sql}) AS books")
	end


	def student?
    	self.role == 'Alumno'
  	end

  	def librarian?
   		self.role == 'Bibliotecario'
 	end

 	def preceptor?
   		self.role == 'Preceptor'
 	end

 	def professor?
   		self.role == 'Docente'
 	end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	helper_method :current_user
	#before_action :require_operator


  def current_user
    @current_user ||= User.find_by_id(session[:user_id]) if session[:user_id]
  end

  def require_user
    redirect_to login_path unless current_user
  end

	rescue_from CanCan::AccessDenied do |exception|
   redirect_to root_path, :alert => exception.message
 end


  # def require_operator
   # redirect_to login_path unless current_user.role == 'operator'
  #end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController


	before_action :find_book, only: [:show,:edit,:update,:destroy]

  load_and_authorize_resource

  def index
    @books = Book.all
		if params[:search]
      @books = Book.search(params[:search]).order("created_at DESC")
    else
      @books = Book.all.order('created_at DESC')
		end
  end




  def show

  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to @book
    else
      render :new
    end
  end

  def book_params
      params.require(:book).permit(:isbn, :name, :author, :tag, :published_at, :state)
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to @book
    else
      render :edit
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  def find_book
    @book = Book.find(params[:id])
  end


end

app/controllers/loans_controller.rb
class LoansController < ApplicationController
	before_action :find_loan, only: [:show,:edit,:update,:destroy]

  load_and_authorize_resource

	def index
    @loans = Loan.all
		@loans = @loans.map { |loan| loan.is_expired? }
    if params[:search]
      @loans = Loan.search(params[:search]).order("created_at DESC")
    else
      @loans = Loan.all.order('created_at DESC')
    end
	end

  def show
  end

  def new
    @loan = Loan.new
  end

  def create
    @book = Book.find_by_id(params[:loan][:book_id])

    if @book.available?
      puts loan_params

      @loan = Loan.new(loan_params)
      @loan.save
      redirect_to @loan
    else
			 flash[:alert] ="Libro no disponible"
			 redirect_to loans_path

    end
  end


  #def create
   # @loan = Loan.new(loan_params)
    #if @loan.save
     # redirect_to @loan
    #else
     # render :new
    #end
  #end

  def loan_params
      params.require(:loan).permit(:user_id, :book_id, :initiation_date, :final_date, :state)
  end

  def edit
  end

  def update
    if @loan.update(loan_params)
      redirect_to @loan
    else
      render :edit
    end
  end

  def destroy
    @loan.destroy
    redirect_to loans_path
  end

  def find_loan
    @loan = Loan.find(params[:id])
  end


end

app/controllers/session_controller.rb
class SessionController < ApplicationController
	layout 'application'
	def new
 #necesito el formulario para la creación de la sesion
	end

	def create

	  user = User.find_by_email(params[:session][:email])
	  if user && user.authenticate(params[:session][:password])
	    session[:user_id] = user.id
	    redirect_to books_path
	  else
			flash[:alert] = "Email o Contraseña incorrectos"
	    redirect_to welcome_index_path

	  end
	end

	def destroy
	  session[:user_id] = nil
	  redirect_to welcome_index_path
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	before_action :find_user, only: [:show,:edit,:update,:destroy]

  load_and_authorize_resource

 	def index
    @users = User.all
    if params[:search]
      @users = User.search(params[:search]).order("created_at DESC")
    else
      @users = User.all.order('created_at DESC')
    end
	end

  def show
  end

  def new
    @user = User.new
  end


  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :new
    end
  end

  def user_params
      params.require(:user).permit(:first_name, :last_name, :dni, :email, :telephone, :role, :password, :password_confirmation)
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def find_user
    @user = User.find(params[:id])
  end


end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/loans_helper.rb
module LoansHelper
end

app/helpers/session_helper.rb
module SessionHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/books/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-5">
      <div class="card mt-5">
        <% if @book.new_record? %>
          <div class="card-header font-weight-bold">Agregar Libro</div>
        <% else %>
          <div class="card-header font-weight-bold">Editar Libro</div>
        <% end %>
          <%= form_for @book do |f| %>
          <div class="card-body">
             <div class="form-group">
              <%= f.label :Isbn %>
              <%= f.number_field :isbn, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.label :Titulo %>
              <%= f.text_field :name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.label :Autor %>
              <%= f.text_field :author, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :Fecha_de_publicacion %>
              <%= f.date_field :published_at, class: "form-control" %>
            </div>

            <% unless @book.new_record? %>
             <div class="form-group">
              <%= f.label :Estado %><br>
              <%= f.select(:state, options_for_select(([[ 'Disponible', 'available'] , [ 'Prestado','loaned']]), @book.state))%>
              </div>
            <% end %>


          </div>
          <div class="card-footer text-right">
            <%= link_to "Cancelar", books_path, class: "btn btn-outline-dark" %>
            <% if @book.new_record? %>
              <%= f.submit "Crear Libro" , class: "btn btn-success" %>
            <% else %>
              <%= f.submit "Guardar Cambios" , class: "btn btn-success" %>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/books/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">

  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item">
        <%= link_to('Home', welcome_index_path, class:'nav-link sr-only') %>
      </li>
      <li class="nav-item">
        <%= link_to('Libros', books_path, class:'nav-link sr-only') %>
      </li>
      <li class="nav-item">
        <%= link_to('Préstamos', loans_path, class:'nav-link sr-only') %>
      </li>
      <li>
        <%= link_to('Salir', welcome_index_path, class:'btn btn-secondary') %>
      </li>
    </ul>
  </div>
</nav>

app/views/books/edit.html.erb
<%= render "books/form" %>

app/views/books/index.html.erb
<%= render "navegacion/navbar"%>

<div class="books-page">
  <div class="container">
    <% if can? :create, Book %>
      <div class="text-right"><%= link_to "Agregar Libro", new_book_path, class: "btn btn-outline-primary rounded-0" %>
      </div>
    <% end %>
    <br></br>
    <h3> LIBROS </h3>

    <%= form_tag(books_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Nombre o Autor" %>
      <%= submit_tag "Buscar" %>
    <% end %>


    <% @books.each do |book| %>
    <div class="card border-dark mb-3" style="max-width: 50rem;margin-top: 1em">
      <div class="card-header"><h4><strong><%= book.name %></strong></h4>
        <h5><%= book.author %></h5></div>
      <div class="card-body text-dark">
        <h5 class="card-title"><%= book.available%></h5>

        <%= link_to "Detalles", book, class: "btn btn-info" %>
      <% if can? :edit, book %>
        <%= link_to "Editar", edit_book_path(book), class: "btn btn-secondary" %>
      <% end %>
       <% if can? :delete, book %>
      <%= link_to "Eliminar", book, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este libro?" } %>
      <% end %>
      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/books/new.html.erb
<%= render "books/form" %>

app/views/books/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, books_path, class: "btn btn-link" %>

    <header class="main">
      <h2>Detalles del libro</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">

      <div class="book-details">

        <dl>
          <dt>ISBN</dt>
          <dd><%= @book.isbn %></dd>
          <dt>Nombre</dt>
          <dd><%= @book.name %></dd>
          <dt>Autor</dt>
          <dd><%= @book.author %></dd>
          <dt>Fecha de publicación</dt>
          <dd><%= @book.published_at %></dd>
          <dt>Disponibilidad</dt>
          <dd><%= @book.available %></dd>
        </dl>

      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblioteca</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-dark bg-dark">
    <a class="navbar-brand">
      <%=image_tag("logo.png", alt: "Example Image", size: "50x50")%>

      <strong> BIBLIOTECA VIRTUAL </strong>
    </a>
  </nav>

  <body>


      <% flash.each do | type, msg | %>
          <div class = "alert alert-danger" >
              <%= msg%>
          </div>
      <% end %>
    <%= yield %>
  </body>
</html>

app/views/loans/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
          <% if @loan.new_record? %>
            <div class="card-header font-weight-bold">Crear Préstamo</div>
          <% else %>
            <div class="card-header font-weight-bold">Guardar Cambios</div>
          <% end %>
            <%= form_for @loan do |f| %>
              <div class="card-body">
                 <div class="form-group">
                  <%= f.label :DNI_usuario %>
                  <%= f.select(:user_id, options_for_select(([nil]+User.all.pluck(:dni, :id)), @loan.user_id))%>
                </div>
                <div class="form-group">
                  <%= f.label :Nombre_libro %>
                  <%= f.select(:book_id, options_for_select(([nil]+Book.all.pluck(:name, :id)), @loan.book_id))%>
                </div>
                <div class="form-group">
                  <%= f.label :Desde %>
                  <%= f.date_field :initiation_date, class: "form-control" %>
                </div>

                <div class="form-group">
                  <%= f.label :Hasta %>
                  <%= f.date_field :final_date, class: "form-control" %>
                </div>


                <% unless @loan.new_record? %>
                 <div class="form-group">
                  <%= f.label :Estado %><br>
                  <%= f.select(:state, options_for_select(([[ 'Activo', 'actived'] , [ 'Expirado','expired'] , [ 'Finalizado', 'finished']]), @loan.state))%>
                  </div>
                <% end %>

              </div>
              <div class="card-footer text-right">
                <%= link_to "Cancelar", loans_path, class: "btn btn-outline-dark" %>
                <% if @loan.new_record? %>
                  <%= f.submit "Crear Préstamo" , class: "btn btn-success" %>
                <% else %>
                  <%= f.submit "Guardar Cambios" , class: "btn btn-success" %>
                <% end %>
              </div>
            <% end %>
      </div>
    </div>
  </div>

app/views/loans/edit.html.erb
<%= render "loans/form" %>

app/views/loans/index.html.erb
<%= render "navegacion/navbar"%>



<div class="books-page">
  <div class="container">
    <% if can? :create, Loan %>
      <div class="text-right"><%= link_to "Nuevo Préstamo", new_loan_path, class: "btn btn-outline-primary rounded-0" %>
      </div>
    <% end %>
    <br></br>
    <h3> PRÉSTAMOS </h3>

<!--BUSCADOR -->
    <%= form_tag(loans_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Id usuario o Estado" %>
      <%= submit_tag "Buscar" %>
    <% end %>


    <% @loans.each do |loan| %>
  <% if can? :read, loan %>
    <div class="card border-dark mb-3" style="max-width: 50rem;margin-top: 1em">
        <div class="card-header">
          <h4 class="card-title">

            Préstamo ID #<strong><%= loan.id %></strong> Estado: <strong><%= loan.estado %></strong>
            <h5><strong><%= loan.book.name %></strong></h5></div>
        <div class="card-body text-dark">
            <h6> Retirado por: <strong><%= loan.user.last_name %> <%= loan.user.first_name %></strong> | Usuario #<%= loan.user_id %></h6>
          <p class="card-text"> Vencimiento: <strong><%= loan.final_date %></strong></p>

          <%= link_to "Detalles", loan, class: "btn btn-info" %>


          <% if can? :edit, loan %>
            <%= link_to "Editar", edit_loan_path(loan), class: "btn btn-secondary" %>
          <% end %>

          <% if can? :delete, loan %>
          <%= link_to "Eliminar", loan, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este préstamo?" } %>
          <% end %>
        </div>
    </div>
  <%end%>
    <%end%>

  </div>
</div>

app/views/loans/new.html.erb
<%= render "loans/form" %>

app/views/loans/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, loans_path, class: "btn btn-black" %>

    <header class="main">
      <h2>Detalles del préstamo</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">

      <div class="book-details">

        <dl>
          <dt>ID de préstamo</dt>
          <dd><%= @loan.id %></dd>
          <dt>Libro</dt>
          <dd><%= @loan.book.isbn %> <%= @loan.book.name %></dd>
          <dt>Retirado por</dt>
          <dd><%= @loan.user.last_name%> <%= @loan.user.first_name %></dd>
          <dt>Desde</dt>
          <dd><%= @loan.initiation_date %></dd>
          <dt>Hasta</dt>
          <dd><%= @loan.final_date %></dd>
          <dt>Estado</dt>
          <dd><%= @loan.estado %></dd>
        </dl>

      </div>
    </div>
  </div>
</div>

app/views/navegacion/_navbar.html.erb
<nav class="navbar is-primary" role="navigation" aria-label="main navigation">
	<div id="navbarBasicExample" class="navbar-menu">
	  <div class="navbar-start">
		<% if can? :read, User %>
          <%= link_to('Usuarios', users_path, class:'btn btn-dark') %>
      	<% end %>
	    <%= link_to('Libros', books_path, class:'btn btn-dark') %>
	    <%= link_to('Préstamos', loans_path, class:'btn btn-dark') %>
	    <%= link_to('Cerrar Sesión', logout_path, class:'btn btn-outline-secondary') %>
	  </div>


	</div>
</nav>

app/views/session/new.html.erb
<p id="notice"><%= notice %></p>

  <%= form_for(:session, url: login_path) do |f| %>
    <%= f.email_field :email, :placeholder => 'Email', required: true %>
    <%= f.password_field :password, :placeholder => 'Password', required: true %>
    <%= f.submit "Ingresar"%>
<br>

app/views/users/_form.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-6">
      <div class="card mt-5">
        <% if @user.new_record? %>
          <div class="card-header font-weight-bold">Agregar Usuario</div>
        <% else %>
          <div class="card-header font-weight-bold">Guardar Cambios</div>
        <% end %>

          <%= form_for @user do |f| %>
          <div class="card-body">
             <div class="form-group">
              <%= f.label :Apellido %>
              <%= f.text_field :last_name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.label :Nombre %>
              <%= f.text_field :first_name, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.label :DNI %>
              <%= f.number_field :dni, class: "form-control" %>
            </div>

            <div class="form-group">
              <%= f.label :Email %>
              <%= f.email_field :email, class: "form-control" %>
            </div>
            <div class="form-group">
              <%= f.label :Teléfono %>
              <%= f.phone_field :telephone, class: "form-control" %>
            </div>


             <div class="form-group">
              <%= f.label :Tipo_de_usuario %><br>
              <%= f.select(:role, options_for_select(([[ 'Alumno', 'Alumno'] , [ 'Docente','Docente'] , [ 'Preceptor','Preceptor']]), @user.role))%>
              </div>


            <div class="form-group">
              <%= f.label :Contraseña%>
              <%= f.password_field :password, class: "form-control", autofocus: true %>
            </div>
            <div class="form-group">
              <%= f.label :Confirmar_Contraseña%>
              <%= f.password_field :password_confirmation, class: "form-control", autofocus: true %>
            </div>


          </div>
          <div class="card-footer text-right">
            <%= link_to "Cancelar", users_path, class: "btn btn-outline-dark" %>
            <% if @user.new_record? %>
              <%= f.submit "Crear Usuario" , class: "btn btn-success" %>
            <% else %>
              <%= f.submit "Guardar Cambios" , class: "btn btn-success" %>
            <% end %>
          </div>
          <% end %>
      </div>
    </div>
  </div>

app/views/users/edit.html.erb
<%= render "users/form" %>

app/views/users/index.html.erb
<%= render "navegacion/navbar"%>


<div class="books-page">
  <div class="container">
    <% if can? :create, User %>
      <div class="text-right"><%= link_to "Agregar Usuario", new_user_path, class: "btn btn-outline-primary rounded-0" %>
      </div>
    <%end%>
    <h3> USUARIOS </h3>

    <%= form_tag(users_path, :method => "get", id: "search-form") do %>
      <%= text_field_tag :search, params[:search], placeholder: "Apellido o DNI" %>
      <%= submit_tag "Buscar" %>
    <% end %>



    <% @users.each do |user| %>
    <div class="card border-dark mb-3" style="max-width: 50rem;margin-top: 1em">
        <div class="card-header">
          <h4 class="card-title">
           Usuario ID#<%= user.id %> <strong> <%= user.last_name %> <%= user.first_name %> </strong>
          </h4>
          <h5>Tipo de Usuario: <strong><%= user.role %></strong></h5></div>
      <div class="card-body text-dark">
          <p class="card-text"><%= user.email%></p>
          <%= link_to "Detalles", user, class: "btn btn-info" %>

          <% if can? :edit, User %>
           <%= link_to "Editar", edit_user_path(user), class: "btn btn-secondary" %>
          <% end %>
          <% if can? :edit, User %>
            <%= link_to "Eliminar", user, class: "btn btn-danger", method: :delete, data: { confirm: "¿Estás seguro de eliminar este usuario?" } %>
          <% end %>

        </div>
    </div>
    <% end %>
  </div>
</div>

app/views/users/new.html.erb
<%= render "users/form" %>

app/views/users/show.html.erb
<div class="book-page">
  <div class="container">
    <%= link_to "&larr; Volver".html_safe, users_path, class: "btn btn-link" %>

    <header class="main">
      <h2>Detalles del Usuario</h2>
    </header>

    <div class="book d-flex flex-sm-row align-items-center align-items-sm-start">
   
      <div class="book-details">
        
        <dl>
          <dt>ID</dt>
          <dd><%= @user.id %></dd>
          <dt>Apellido</dt>
          <dd><%= @user.last_name %></dd>
          <dt>Nombre</dt>
          <dd><%= @user.first_name %></dd>
          <dt>DNI</dt>
          <dd><%= @user.dni %></dd>
          <dt>Email</dt>
          <dd><%= @user.email %></dd>
          <dt>Teléfono</dt>
          <dd><%= @user.telephone %></dd>
          <dt>Tipo de Usuario</dt>
          <dd><%= @user.role %></dd>
        </dl>
        
      </div>
    </div>
  </div>
</div>

app/views/welcome/index.html.erb
<div class="container">
    <div class="row justify-content-center">
      <div class="col-sm-5">
        <div class="card mt-5 mb-2">
          <div class="card-header">Iniciar Sesión
          </div>
          <div class="card-body">

            <%= form_for(:session, url: login_path) do |f| %>
              <div class="form-group">
                <%= f.label :email %>
                <%= f.email_field :email, class: "form-control", autofocus: true %>
              </div>

              <div class="form-group">
                <%= f.label :password %>
                <%= f.password_field :password, class: "form-control", autocomplete: "off" %>
              </div>


              <div class="text-right">
                <%= f.submit "Ingresar", class: "btn btn-outline-success" %>
              </div>
            <% end %>
          </div>
        </div>


      </div>
    </div>
  </div>